name: Workflow for API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RESTBOOKER_USERNAME: ${{ secrets.RESTBOOKER_USERNAME }}
      RESTBOOKER_PASSWORD: ${{ secrets.RESTBOOKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run API Tests
        run: mvn clean test -Pregression -q

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: allure-results
          path: allure-results
